{% set name = "lava-dnf" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava-dnf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b55268b63024a76e1e5fb49afe9c395bb8461a4f98dfd386be52b5084654662
  patches:
    - 36.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }},<3.11
    - numpy
    - lava
    - scipy
    - asteval
    - pandas

test:
  requires:
    - pytest
    - nbformat
    - nbconvert
    - nb_conda_kernels
    - ipykernel
    - jupyter
    - python {{ python_min }}
  source_files:
    - tests
    - tutorials
  imports:
    - lava.lib.dnf.kernels.kernels
    - lava.lib.dnf.connect.connect
    - lava.lib.dnf.operations.operations
  # commands:
  #   - python -m ipykernel install --name python3 --user
  #   - python -m unittest

about:
  home: https://github.com/lava-nc/lava-dnf
  summary: lava-dnf is a library within the Lava software framework. lava-dnf provides processes and other software infrastructure to build architectures composed of DNFs.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - mgkwill
